### PR TITLE
Initial API support

### PR DESCRIPTION
**Pull request by 98lenvi**
## linked to #2 

Changes:
- Added data folder
  - Added models.dart
  - Added services.dart

Models file will contain the models for converting JSON returned from the API to Flutter objects. We need to discuss the naming for the objects ( I haven't paid much attention to it since it is better that @Sameerkash decide on the naming).

The services file will have the methods to make the API request. Right now only one method for calling https://api.rootnet.in/covid19-in/stats/latest has been created. 

I have made modifications to the home_screen.dart file ( you can extend support for displaying the data from there).

### CODE REVIEW

**Comment by 98lenvi** [comment]
Possible improvements:
- Moving the entire JSON -> Objects conversion to an Isolate (at a later stage).

**Comment by sameeerkashyap** [comment]
It would be more organized if there's a models folder instead of a file and all models have its on file unless they're closely related. If that's possible, try this change. Else it'll do for now.

**Comment by 98lenvi** [comment]
I agree with you on that, I'll do it (unless you've already started). What do you think about the naming? @Sameerkash

**Comment by sameeerkashyap** [comment]
No you can continue I'll be doing UI, naming is fine as long it's relevent.

**Comment by 98lenvi** [comment]
@Sameerkash, check now!

**Comment by sameeerkashyap** [comment]
This looks great. You can also check out other options to parse JSON like [json_seralizable](https://pub.dev/packages/json_serializable)

**Pull request merged**
